In [131]:
import numpy as np
import time



class Units():
    def __init__(self):
        self.E_list = [[17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32], 
                       [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]
        self.pawn_Y = (1, 1, 1, 2)
        self.pawn_X = (0, -1, 1, 0)
        self.rook_Y = (1, 0, 0, -1)
        self.rook_X = (0, -1, 1, 0)
        self.knight_Y = (2, 1, -1, -2, -2, -1, 1, 2)
        self.knight_X = (1, 2, 2, 1, -1, -2, -2, -1)
        self.bishop_Y = (1, 1, -1, -1)
        self.bishop_X = (-1, 1, 1, -1)
        self.king_Y = (1, 1, 0, -1, -1, -1, 0, 1)
        self.king_X = (0, 1, 1, 1, 0, -1, -1, -1)
        self.queen_Y = (1, 1, 0, -1, -1, -1, 0, 1)
        self.queen_X = (0, 1, 1, 1, 0, -1, -1, -1)
        self.piece_value_Dict = [5,5,5,100,20,5,5,5,1,1,1,1,1,1,1,1,
                                 1,1,1,1,1,1,1,1,5,5,5,100,20,5,5,5]
        
        
    def pawn_action(self, u, a, b):
        Y_m = self.pawn_Y[a]
        X_m = self.pawn_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):
                if (Y_0 == 1) and (a == 3):
                    if b[Y_0+1,X_0] == 0:
                        if b[Y_0+Y_m,X_0+X_m] == 0:
                            return (Y_0+Y_m), (X_0+X_m), -1
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
                elif (a == 1) or (a == 2):
                    if (b[Y_0+Y_m,X_0+X_m] in self.E_list[0]):
                        return (Y_0+Y_m), (X_0+X_m), self.piece_value_Dict[int(b[Y_0+Y_m,X_0+X_m])-1]
                    else:
                        return Y_0, X_0, -2
                else:
                    if b[Y_0+Y_m,X_0+X_m] == 0:
                        return (Y_0+Y_m), X_0, -1
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):
                if (Y_0 == 6) and (a == 3):
                    if b[Y_0-1,X_0] == 0:
                        if b[Y_0-Y_m,X_0] == 0:
                            return (Y_0-Y_m), X_0, -1
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
                elif (a == 1) or (a == 2):
                    if (b[Y_0-Y_m,X_0-X_m] in self.E_list[1]):
                        return (Y_0-Y_m), (X_0-X_m), self.piece_value_Dict[int(b[Y_0-Y_m,X_0-X_m])-1]
                    else:
                        return Y_0, X_0, -2
                else:
                    if b[Y_0-Y_m,X_0-Y_m] == 0:
                        return (Y_0-Y_m), X_0, -1
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        
        
    def pawn_influence(self, u, b, ib, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+1) >= 0) and ((Y_0+1) <= 7) and (b[Y_0+1,X_0] == 0):
                ib[Y_0+1,X_0] = u
                p[u-1].append(0)
                if ((Y_0+2) >= 0) and ((Y_0+2) <= 7) and (b[Y_0+2,X_0] == 0) and (Y_0 == 1):
                    ib[Y_0+2,X_0] = u
                    p[u-1].append(3)
            if ((Y_0+1) >= 0) and ((Y_0+1) <= 7) and ((X_0+1) >= 0) and ((X_0+1) <= 7):
                if b[Y_0+1,X_0+1] in self.E_list[0]:
                    ib[Y_0+1,X_0+1] = u
                    p[u-1].append(2)
            if ((Y_0+1) >= 0) and ((Y_0+1) <= 7) and ((X_0-1) >= 0) and ((X_0-1) <= 7):
                if b[Y_0+1,X_0-1] in self.E_list[0]:
                    ib[Y_0+1,X_0-1] = u
                    p[u-1].append(1)
        else:
            if ((Y_0-1) >= 0) and ((Y_0-1) <= 7) and (b[Y_0-1,X_0] == 0):
                ib[Y_0-1,X_0] = u
                p[u-1].append(0)
                if ((Y_0-2) >= 0) and ((Y_0-2) <= 7) and (b[Y_0-2,X_0] == 0) and (Y_0 == 6):
                    ib[Y_0-2,X_0] = u
                    p[u-1].append(3)
            if ((Y_0-1) >= 0) and ((Y_0-1) <= 7) and ((X_0+1) >= 0) and ((X_0+1) <= 7):
                if (b[Y_0-1,X_0+1] in self.E_list[1]):
                    ib[Y_0-1,X_0+1] = u
                    p[u-1].append(1)
            if ((Y_0-1) >= 0) and ((Y_0-1) <= 7) and ((X_0-1) >= 0) and ((X_0-1) <= 7):
                if (b[Y_0-1,X_0-1] in self.E_list[1]):
                    ib[Y_0-1,X_0-1] = u
                    p[u-1].append(2)
        
    
    def rook_action(self, u, a, i, b):
        Y_m = self.rook_Y[a]
        X_m = self.rook_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0+x*Y_m,X_0+x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]):
                            return (Y_0+i*Y_m), (X_0+i*X_m), self.piece_value_Dict[int(b[Y_0+i*Y_m,X_0+i*X_m])-1]
                        elif (b[Y_0+i*Y_m,X_0+i*X_m] == 0):
                            return (Y_0+i*Y_m), (X_0+i*X_m), -1
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0-x*Y_m,X_0-x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]):
                            return (Y_0-i*Y_m), (X_0-i*X_m), self.piece_value_Dict[int(b[Y_0-i*Y_m,X_0-i*X_m])-1]
                        elif (b[Y_0-i*Y_m,X_0-i*X_m] == 0):
                            return (Y_0-i*Y_m), (X_0-i*X_m), -1
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            return Y_0, X_0, -2
    
    
    def rook_influence(self, u, b, ib, k, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,4):
                Y_m = self.rook_Y[a]
                X_m = self.rook_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0+i*Y_m,X_0+i*X_m])
                    if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                        if (b[Y_0+i*Y_m,X_0+i*X_m] == 0) or (int(b[Y_0+i*Y_m,X_0+i*X_m][0]) in self.E_list[0]):
                            if i == 1:
                                p[u-1].append(a)
                            ib[Y_0+i*Y_m,X_0+i*X_m] = u
                            if b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]:
                                if b[Y_0+i*Y_m,X_0+i*X_m] == 28:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
        else:
            for a in range(0,4):
                Y_m = self.rook_Y[a]
                X_m = self.rook_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0-i*Y_m,X_0-i*X_m])
                    if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                        if (b[Y_0-i*Y_m,X_0-i*X_m] == 0) or (int(b[Y_0-i*Y_m,X_0-i*X_m][0]) in self.E_list[1]):
                            if i == 1:
                                p[u-1].append(a)
                            ib[Y_0-i*Y_m,X_0-i*X_m] = u
                            if b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]:
                                if b[Y_0-i*Y_m,X_0-i*X_m] == 4:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
    
    
    def knight_action(self, u, a, b):
        Y_m = self.knight_Y[a]
        X_m = self.knight_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):    
                if (b[Y_0+Y_m,X_0+X_m] in self.E_list[0]):
                    return (Y_0+Y_m), (X_0+X_m), self.piece_value_Dict[int(b[Y_0+Y_m,X_0+X_m])-1]
                elif (b[Y_0+Y_m,X_0+X_m] == 0):
                    return (Y_0+Y_m), (X_0+X_m), -1
                else:
                    return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):    
                if (b[Y_0-Y_m,X_0-X_m] in self.E_list[1]):
                    return (Y_0-Y_m), (X_0-X_m), self.piece_value_Dict[int(b[Y_0-Y_m,X_0-X_m])-1]
                elif (b[Y_0-Y_m,X_0-X_m] == 0):
                    return (Y_0-Y_m), (X_0-X_m), -1
                else:
                    return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
    
    
    def knight_influence(self, u, b, ib, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,8):
                Y_m = self.knight_Y[a]
                X_m = self.knight_X[a]
                if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):
                    if (b[Y_0+Y_m,X_0+X_m] == 0) or (int(b[Y_0+Y_m,X_0+X_m][0]) in self.E_list[0]):
                        p[u-1].append(a)
                        ib[Y_0+Y_m,X_0+X_m] = u
        else:
            for a in range(0,8):
                Y_m = self.knight_Y[a]
                X_m = self.knight_X[a]
                if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):
                    if (b[Y_0-Y_m,X_0-X_m] == 0) or (int(b[Y_0-Y_m,X_0-X_m][0]) in self.E_list[1]):
                        p[u-1].append(a)
                        ib[Y_0-Y_m,X_0-X_m] = u
    
    
    def bishop_action(self, u, a, i, b):
        Y_m = self.bishop_Y[a]
        X_m = self.bishop_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0+x*Y_m,X_0+x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]):
                            return (Y_0+i*Y_m), (X_0+i*X_m), self.piece_value_Dict[int(b[Y_0+i*Y_m,X_0+i*X_m])-1]
                        elif (b[Y_0+i*Y_m,X_0+i*X_m] == -1):
                            return (Y_0+i*Y_m), (X_0+i*X_m), -1
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0-x*Y_m,X_0-x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]):
                            return (Y_0-i*Y_m), (X_0-i*X_m), self.piece_value_Dict[int(b[Y_0-i*Y_m,X_0-i*X_m])-1]
                        elif (b[Y_0-i*Y_m,X_0-i*X_m] == -1):
                            return (Y_0-i*Y_m), (X_0-i*X_m), -1
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            return Y_0, X_0, -2
        
        
    def bishop_influence(self, u, b, ib, k, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,4):
                Y_m = self.bishop_Y[a]
                X_m = self.bishop_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0+i*Y_m,X_0+i*X_m])
                    if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                        if (b[Y_0+i*Y_m,X_0+i*X_m] == 0) or (int(b[Y_0+i*Y_m,X_0+i*X_m][0]) in self.E_list[0]):
                            p[u-1].append(a)
                            ib[Y_0+i*Y_m,X_0+i*X_m] = u
                            if b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]:
                                if b[Y_0+i*Y_m,X_0+i*X_m] == 28:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
        else:
            for a in range(0,4):
                Y_m = self.bishop_Y[a]
                X_m = self.bishop_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0-i*Y_m,X_0-i*X_m])
                    if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                        if (b[Y_0-i*Y_m,X_0-i*X_m] == 0) or (int(b[Y_0-i*Y_m,X_0-i*X_m][0]) in self.E_list[1]):
                            p[u-1].append(a)
                            ib[Y_0-i*Y_m,X_0-i*X_m] = u
                            if b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]:
                                if b[Y_0-i*Y_m,X_0-i*X_m] == 4:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
    
    
    def king_action(self, u, a, b):
        Y_m = self.king_Y[a]
        X_m = self.king_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):    
                if (b[Y_0+Y_m,X_0+X_m] in self.E_list[0]):
                    return (Y_0+Y_m), (X_0+X_m), self.piece_value_Dict[int(b[Y_0+Y_m,X_0+X_m])-1]
                elif (b[Y_0+Y_m,X_0+X_m] == 0):
                    return (Y_0+Y_m), (X_0+X_m), 0
                else:
                    return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
        else:
            if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):    
                if (b[Y_0-Y_m,X_0-X_m] in self.E_list[1]):
                    return (Y_0-Y_m), (X_0-X_m), self.piece_value_Dict[int(b[Y_0-Y_m,X_0-X_m])-1]
                elif (b[Y_0-Y_m,X_0-X_m] == 0):
                    return (Y_0-Y_m), (X_0-X_m), 0
                else:
                    return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
    
    
    def king_influence(self, u, b, ib, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,8):
                Y_m = self.king_Y[a]
                X_m = self.king_X[a]
                if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):
                    if (b[Y_0+Y_m,X_0+X_m] == 0) or (int(b[Y_0+Y_m,X_0+X_m][0]) in self.E_list[0]):
                        p[u-1].append(a)
                        ib[Y_0+Y_m,X_0+X_m] = u
        else:
            for a in range(0,8):
                Y_m = self.king_Y[a]
                X_m = self.king_X[a]
                if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):
                    if (b[Y_0-Y_m,X_0-X_m] == 0) or (int(b[Y_0-Y_m,X_0-X_m][0]) in self.E_list[1]):
                        p[u-1].append(a)
                        ib[Y_0-Y_m,X_0-X_m] = u
    
    
    def matilda_action(self, u, a, i, b):
        Y_m = self.queen_Y[a]
        X_m = self.queen_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0+x*Y_m,X_0+x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]):
                            return (Y_0+i*Y_m), (X_0+i*X_m), self.piece_value_Dict[int(b[Y_0+i*Y_m,X_0+i*X_m])-1]
                        elif (b[Y_0+i*Y_m,X_0+i*X_m] == 0):
                            return (Y_0+i*Y_m), (X_0+i*X_m), -1
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0-x*Y_m,X_0-x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]):
                            return (Y_0-i*Y_m), (X_0-i*X_m), self.piece_value_Dict[int(b[Y_0-i*Y_m,X_0-i*X_m])-1]
                        elif (b[Y_0-i*Y_m,X_0-i*X_m] == 0):
                            return (Y_0-i*Y_m), (X_0-i*X_m), -1
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            return Y_0, X_0, -2
    
    
    def matilda_influence(self, u, b, ib, k, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,8):
                Y_m = self.queen_Y[a]
                X_m = self.queen_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0+i*Y_m,X_0+i*X_m])
                    if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                        if (b[Y_0+i*Y_m,X_0+i*X_m] == 0) or (int(b[Y_0+i*Y_m,X_0+i*X_m][0]) in self.E_list[0]):
                            p[u-1].append(a)
                            ib[Y_0+i*Y_m,X_0+i*X_m] = u
                            if b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]:
                                if b[Y_0+i*Y_m,X_0+i*X_m] == 28:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
        else:
            for a in range(0,8):
                Y_m = self.queen_Y[a]
                X_m = self.queen_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0-i*Y_m,X_0-i*X_m])
                    if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                        if (b[Y_0-i*Y_m,X_0-i*X_m] == 0) or (int(b[Y_0-i*Y_m,X_0-i*X_m][0]) in self.E_list[1]):
                            p[u-1].append(a)
                            ib[Y_0-i*Y_m,X_0-i*X_m] = u
                            if b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]:
                                if b[Y_0-i*Y_m,X_0-i*X_m] == 4:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
    
    
    def unit_action(self, u, a, i, b):
        if ((u >= 9) and (u <= 16)) or ((u >= 17) and (u <= 24)):
            return self.pawn_action(u, a, b)
        elif (u == 1) or (u == 8) or (u == 25) or (u == 32):
            return self.rook_action(u, a, i, b)
        elif (u == 2) or (u == 7) or (u == 26) or (u == 31):
            return self.knight_action(u, a, b)
        elif (u == 3) or (u == 6) or (u == 27) or (u == 30):
            return self.bishop_action(u, a, i, b)
        elif (u == 4) or (u == 28):
            return self.king_action(u, a, b)
        elif (u == 5) or (u == 29):
            return self.matilda_action(u, a, i, b)
    
    
    def unit_influence(self, u, b, ib, k, p):
        if ((u >= 9) and (u <= 16)) or ((u >= 17) and (u <= 24)):
            return self.pawn_influence(u, b, ib, p)
        elif (u == 1) or (u == 8) or (u == 25) or (u == 32):
            return self.rook_influence(u, b, ib, k, p)
        elif (u == 2) or (u == 7) or (u == 26) or (u == 31):
            return self.knight_influence(u, b, ib, p)
        elif (u == 3) or (u == 6) or (u == 27) or (u == 30):
            return self.bishop_influence(u, b, ib, k, p)
        elif (u == 4) or (u == 28):
            return self.king_influence(u, b, ib, p)
        elif (u == 5) or (u == 29):
            return self.matilda_influence(u, b, ib, k, p)
        
        
        
class Chess():
    def __init__(self):
        self.units = Units()
        
        
    def init_protocol(self):
        self.board = np.array([[ 1, 2, 3, 4, 5, 6, 7, 8],
                               [ 9,10,11,12,13,14,15,16],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [17,18,19,20,21,22,23,24],
                               [25,26,27,28,29,30,31,32]])
        return self.board.flatten().reshape(1,64).astype('float32')
    
        
    def action_protocol(self, p, u, a, i):
        self.reward = [-1,-1,-1]
        self.influence_board_protocol()
        if np.any(self.board==u):
            if a in self.p_actions[u-1]:
                Y, X, self.reward[2] = self.units.unit_action(u, a, i+1, self.board)
                Y_0, X_0 = np.where(self.board==u)
                self.board[Y,X] = u
                if self.reward[2] != -2:
                    self.board[Y_0,X_0] = 0
                if (self.reward[2] != -1) and (self.reward[2] != -2):
                    self.reward[0], self.reward[1] = self.reward[2], self.reward[2]
            else:
                self.reward[1] = -2
        else:
            self.reward[0] = -2
        self.win_check_protocol(p)
        return self.board.flatten().reshape(1,64).astype('float32'), self.reward
            
    
    def win_check_protocol(self, p):
        self.influence_board_protocol()
        T = self.surrounded_protocol(p)
        A = len(self.line_of_fire_protocol(p))
        if A > 1:
            if T:
                self.reward[0], self.reward[1], self.reward[2] = 100, 100, 100
        elif A == 1:
            if T:
                if self.protecc_ex_protocol(p) or self.protecc_bl_protocol(p):
                    return
                else:
                    self.reward[0], self.reward[1], self.reward[2] = 100, 100, 100
            else:
                return
        else:
            return
                
    
    def influence_board_protocol(self):
        self.p_actions = [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                          [],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
        self.influence_board = np.zeros((32,8,8))
        self.coordinates_line_of_fire = []
        for y in range(0,8):
            for x in range(0,8):
                if self.board[y,x] != 0:
                    self.units.unit_influence(self.board[y,x], self.board, 
                                              self.influence_board[self.board[y,x]-1], 
                                              self.coordinates_line_of_fire, self.p_actions)
    
    
    def line_of_fire_protocol(self,p):
        self.k_line_of_fire = []
        if p == 0:
            Y_k, X_k = np.where(self.board==28)
            for z in range(0,16):
                if self.influence_board[z,Y_k,X_k]:
                    self.k_line_of_fire.append(self.influence_board[z,Y_k,X_k])
            return self.k_line_of_fire
        else:
            Y_k, X_k = np.where(self.board==4)
            for z in range(16,32):
                if self.influence_board[z,Y_k,X_k]:
                    self.k_line_of_fire.append(self.influence_board[z,Y_k,X_k])
            return self.k_line_of_fire
    
    
    def surrounded_protocol(self,p):
        s = 0
        if p == 0:
            A = np.where(self.influence_board[27]==28)
            for x in range(0,len(A[0])):
                self.influencers = []
                Y_m = A[0][x]
                X_m = A[1][x]
                for z in range(0,16):
                    if self.influence_board[z,Y_m,X_m]:
                        s += 1
                        break
            if s == len(A[0]):
                return True
        else:
            A = np.where(self.influence_board[3]==4)
            for x in range(0,len(A[0])):
                self.influencers = []
                Y_m = A[0][x]
                X_m = A[1][x]
                for z in range(16,32):
                    if self.influence_board[z,Y_m,X_m]:
                        s += 1
                        break
            if s == len(A[0]):
                return True
    
    
    def protecc_ex_protocol(self,p):
        for u in self.k_line_of_fire:
            Y, X = np.where(self.board==u)
            if p == 0:
                for z in range(16,32):
                    if self.influence_board[z,Y,X]:
                        return True
            else:
                for z in range(0,16):
                    if self.influence_board[z,Y,X]:
                        return True
        return False
       
    
    def protecc_bl_protocol(self,p):
        if p == 0:
            for x in self.coordinates_line_of_fire:
                for y in x:
                    for z in range(16,32):
                        if z != 27:
                            if int(self.influence_board[z,y[0],y[1]]):
                                return True
            return False
        else:
            for x in self.coordinates_line_of_fire:
                for y in x:
                    for z in range(0,16):
                        if z != 3:
                            if int(self.influence_board[z,y[0],y[1]]):
                                return True
            return False

game = Chess()
game.init_protocol()
game.action_protocol(1, 32, 0, 3)
print(game.reward)

[-1, -2, -1]


In [132]:
import tensorflow as tf
learning_rate = 0.0000001

graph = tf.Graph()
with graph.as_default():
    tf_game_state = tf.placeholder(tf.float32, shape=[1,64])
    tf_game_state_U = tf.placeholder(tf.float32, shape=[1,65])
    tf_game_state_UA = tf.placeholder(tf.float32, shape=[1,66])
    
    next_Q_units = tf.placeholder(tf.float32, shape=[1,16])
    next_Q_actions = tf.placeholder(tf.float32, shape=[1,8])
    next_Q_intensity = tf.placeholder(tf.float32, shape=[1,7])
    
    stateU_weights = {'W1' : tf.Variable(tf.random_uniform([64,64],0,1)),
                     'W2' : tf.Variable(tf.random_uniform([64,16],0,1))
                    }
    
    stateA_weights = {'W1' : tf.Variable(tf.random_uniform([65,65],0,1)),
                      'W2' : tf.Variable(tf.random_uniform([65,8],0,1))
                     }
    
    stateI_weights = {'W1' : tf.Variable(tf.random_uniform([66,66],0,1)),
                       'W2' : tf.Variable(tf.random_uniform([66,7],0,1))
                      }
    
    def Q_units(x):
        layer_1 = tf.matmul(x, stateU_weights['W1'])
        layer_out = tf.matmul(layer_1, stateU_weights['W2'])
        return layer_out
    
    def Q_actions(x):
        layer_1 = tf.matmul(x, stateA_weights['W1'])
        layer_out = tf.matmul(layer_1, stateA_weights['W2'])
        return layer_out
    
    def Q_intensity(x):
        layer_1 = tf.matmul(x, stateI_weights['W1'])
        layer_out = tf.matmul(layer_1, stateI_weights['W2'])
        return layer_out
    
    
    loss_units = tf.reduce_sum(tf.square(next_Q_units - Q_units(tf_game_state)))
    loss_actions = tf.reduce_sum(tf.square(next_Q_actions - Q_actions(tf_game_state_U)))
    loss_intensity = tf.reduce_sum(tf.square(next_Q_intensity - Q_intensity(tf_game_state_UA)))
    
    trainer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
    
    updateUnits = trainer.minimize(loss_units)
    updateActions = trainer.minimize(loss_actions)
    updateIntensity = trainer.minimize(loss_intensity)
    
    Q_values_U = Q_units(tf_game_state)
    Q_values_A = Q_actions(tf_game_state_U)
    Q_values_I = Q_intensity(tf_game_state_UA)
    
    predict_U = tf.argmax(Q_values_U,1)
    predict_A = tf.argmax(Q_values_A,1)
    predict_I = tf.argmax(Q_values_I,1)
    

In [138]:
import random 
game = Chess()
num_eps = 1
y = 0.9
e_0 = 1
e_1 = 0.9
intensity_units = [1,3,5,6,8,25,27,29,30,32]
units_0 = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
units_1 = [16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
actions = [0,1,2,3,4,5,6,7]
intensity = [0,1,2,3,4,5,6]


with tf.Session(graph=graph) as sess:
    tf.global_variables_initializer().run()
    for i in range(num_eps):
        s = game.init_protocol()
        t=False
        while True:
            print(s)
            U, allU = sess.run([predict_U,Q_values_U], feed_dict={tf_game_state:s})
            if np.random.rand(1) < e_0:
                U = random.sample(units_0,1)
            sU = np.append(s,U).reshape(1,65).astype('float32')
            A, allA = sess.run([predict_A,Q_values_A], feed_dict={tf_game_state_U:sU})
            if np.random.rand(1) < e_0:
                A = random.sample(actions,1)
            if (U[0]+1) in intensity_units:
                t = True
                sUA = np.append(sU,A).reshape(1,66)
                I, allI = sess.run([predict_I,Q_values_I], feed_dict={tf_game_state_UA:sUA})
                if np.random.rand(1) < e_0:
                    I = random.sample(intensity,1)
                print(i,0,U[0]+1,A[0],I[0]+1)
            else:
                print(i,0,U[0]+1,A[0])
            s1, r = game.action_protocol(0, U[0]+1, A[0], I[0])
            U1 = sess.run([predict_U], feed_dict={tf_game_state:s1})
            targetU = allU
            targetU[0,U] = r[0] + y*U1[0]
            _,w1,w2 = sess.run([updateUnits,stateU_weights['W1'],stateU_weights['W2']],
                               feed_dict={tf_game_state:s,next_Q_units:targetU})
            sU1 = np.append(s1,U1).reshape(1,65)
            A1 = sess.run([predict_A], feed_dict={tf_game_state_U:sU1})
            targetA = allA
            targetA[0,A] = r[1] + y*A1[0]
            _,m1,m2 = sess.run([updateActions,stateA_weights['W1'],stateA_weights['W2']],
                               feed_dict={tf_game_state_U:sU,next_Q_actions:targetA})
            if t:
                sUA1 = np.append(sU1,A1).reshape(1,66).astype('float32')
                I1 = sess.run([predict_I], feed_dict={tf_game_state_UA:sUA1})
                targetI = allI
                targetI[0,I] = r[2] + y*I1[0]
                _,m1,m2 = sess.run([updateIntensity,stateA_weights['W1'],stateA_weights['W2']],
                                   feed_dict={tf_game_state_UA:sUA,next_Q_intensity:targetI})
            t = False
            I = [0]
            allI = None
            s = s1
            if r[0] == 100:
                print('Hurray! p1')
                e_0 = 1./((i/10)+1)
                break
            print(s)
            U, allU = sess.run([predict_U,Q_values_U], feed_dict={tf_game_state:s})
            if np.random.rand(1) < e_0:
                U = random.sample(units_0,1)
            sU = np.append(s,U).reshape(1,65).astype('float32')
            A, allA = sess.run([predict_A,Q_values_A], feed_dict={tf_game_state_U:sU})
            if np.random.rand(1) < e_0:
                A = random.sample(actions,1)
            if (U[0]+17) in intensity_units:
                t = True
                sUA = np.append(sU,A).reshape(1,66)
                I, allI = sess.run([predict_I,Q_values_I], feed_dict={tf_game_state_UA:sUA})
                if np.random.rand(1) < e_0:
                    I = random.sample(intensity,1)
                    print(i,1,U[0]+17,A[0],I[0]+1)
            else:
                print(i,1,U[0]+17,A[0])
            s1, r = game.action_protocol(1, U[0]+17, A[0], I[0])
            U1 = sess.run([predict_U], feed_dict={tf_game_state:s1})
            targetU = allU
            targetU[0,U] = r[0] + y*U1[0]
            _,w1,w2 = sess.run([updateUnits,stateU_weights['W1'],stateU_weights['W2']],
                               feed_dict={tf_game_state:s,next_Q_units:targetU})
            sU1 = np.append(s1,U1).reshape(1,65).astype('float32')
            A1 = sess.run([predict_A], feed_dict={tf_game_state_U:sU1})
            targetA = allA
            targetA[0,A] = r[1] + y*A1[0]
            _,m1,m2 = sess.run([updateActions,stateA_weights['W1'],stateA_weights['W2']],
                               feed_dict={tf_game_state_U:sU,next_Q_actions:targetA})
            if t:
                sUA1 = np.append(sU1,A1).reshape(1,66).astype('float32')
                I1 = sess.run([predict_I], feed_dict={tf_game_state_UA:sUA1})
                targetI = allI
                targetI[0,I] = r[2] + y*I1[0]
                _,m1,m2 = sess.run([updateIntensity,stateA_weights['W1'],stateA_weights['W2']],
                               feed_dict={tf_game_state_UA:sUA,next_Q_intensity:targetI})
            t = False
            I = [0]
            allI = None
            s = s1
            if r[0] == 100:
                print('Hurray! p2')
                e_1 = 1./((i/10)+1)
                break

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
   15.  16.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  17.  18.  19.  20.  21.  22.  23.  24.
   25.  26.  27.  28.  29.  30.  31.  32.]]
0 0 10 2
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
   15.  16.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  17.  18.  19.  20.  21.  22.  23.  24.
   25.  26.  27.  28.  29.  30.  31.  32.]]
0 1 25 6 3
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
   15.  16.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  17.  18.  19.  20.  21.  22.  23.  24.
   25.  26.  27.  28.  29.  

In [139]:
print(game.board)

[[ 1  0  3  0  0  6  0  8]
 [ 0  0 31  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 9  0 20  0  0  0  0 16]
 [17 10  0  0 21 22  0  0]
 [ 0 18 26 29  0  0 23  0]
 [ 0  0 28  0  0  0  0 24]
 [ 0  0 27  0  2 30  0 32]]
