In [20]:
import numpy as np
import time



class Units():
    def __init__(self):
        self.E_list = [[17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32], 
                       [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]
        self.pawn_Y = (1, 1, 1, 2)
        self.pawn_X = (0, -1, 1, 0)
        self.rook_Y = (1, 0, 0, -1)
        self.rook_X = (0, -1, 1, 0)
        self.knight_Y = (2, 1, -1, -2, -2, -1, 1, 2)
        self.knight_X = (1, 2, 2, 1, -1, -2, -2, -1)
        self.bishop_Y = (1, 1, -1, -1)
        self.bishop_X = (-1, 1, 1, -1)
        self.king_Y = (1, 1, 0, -1, -1, -1, 0, 1)
        self.king_X = (0, 1, 1, 1, 0, -1, -1, -1)
        self.queen_Y = (1, 1, 0, -1, -1, -1, 0, 1)
        self.queen_X = (0, 1, 1, 1, 0, -1, -1, -1)
        self.piece_value_Dict = [5,5,5,100,20,5,5,5,1,1,1,1,1,1,1,1,
                                 1,1,1,1,1,1,1,1,5,5,5,100,20,5,5,5]
        
        
    def pawn_action(self, u, a, b):
        Y_m = self.pawn_Y[a]
        X_m = self.pawn_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):
                if (Y_0 == 1) and (a == 3):
                    if b[Y_0+1,X_0] == 0:
                        if b[Y_0+Y_m,X_0+X_m] == 0:
                            return (Y_0+Y_m), (X_0+X_m), 0.5
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
                elif (a == 1) or (a == 2):
                    if (b[Y_0+Y_m,X_0+X_m] in self.E_list[0]):
                        return (Y_0+Y_m), (X_0+X_m), self.piece_value_Dict[int(b[Y_0+Y_m,X_0+X_m])-1]
                    else:
                        return Y_0, X_0, -2
                else:
                    if b[Y_0+Y_m,X_0+X_m] == 0:
                        return (Y_0+Y_m), X_0, 0.5
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):
                if (Y_0 == 6) and (a == 3):
                    if b[Y_0-1,X_0] == 0:
                        if b[Y_0-Y_m,X_0] == 0:
                            return (Y_0-Y_m), X_0, 0.5
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
                elif (a == 1) or (a == 2):
                    if (b[Y_0-Y_m,X_0-X_m] in self.E_list[1]):
                        return (Y_0-Y_m), (X_0-X_m), self.piece_value_Dict[int(b[Y_0-Y_m,X_0-X_m])-1]
                    else:
                        return Y_0, X_0, -2
                else:
                    if b[Y_0-Y_m,X_0-Y_m] == 0:
                        return (Y_0-Y_m), X_0, 0.5
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        
        
    def pawn_influence(self, u, b, ib, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+1) >= 0) and ((Y_0+1) <= 7) and (b[Y_0+1,X_0] == 0):
                ib[Y_0+1,X_0] = u
                p[u-1].append(0)
                if ((Y_0+2) >= 0) and ((Y_0+2) <= 7) and (b[Y_0+2,X_0] == 0) and (Y_0 == 1):
                    ib[Y_0+2,X_0] = u
                    p[u-1].append(3)
            if ((Y_0+1) >= 0) and ((Y_0+1) <= 7) and ((X_0+1) >= 0) and ((X_0+1) <= 7):
                if b[Y_0+1,X_0+1] in self.E_list[0]:
                    ib[Y_0+1,X_0+1] = u
                    p[u-1].append(2)
            if ((Y_0+1) >= 0) and ((Y_0+1) <= 7) and ((X_0-1) >= 0) and ((X_0-1) <= 7):
                if b[Y_0+1,X_0-1] in self.E_list[0]:
                    ib[Y_0+1,X_0-1] = u
                    p[u-1].append(1)
        else:
            if ((Y_0-1) >= 0) and ((Y_0-1) <= 7) and (b[Y_0-1,X_0] == 0):
                ib[Y_0-1,X_0] = u
                p[u-1].append(0)
                if ((Y_0-2) >= 0) and ((Y_0-2) <= 7) and (b[Y_0-2,X_0] == 0) and (Y_0 == 6):
                    ib[Y_0-2,X_0] = u
                    p[u-1].append(3)
            if ((Y_0-1) >= 0) and ((Y_0-1) <= 7) and ((X_0+1) >= 0) and ((X_0+1) <= 7):
                if (b[Y_0-1,X_0+1] in self.E_list[1]):
                    ib[Y_0-1,X_0+1] = u
                    p[u-1].append(1)
            if ((Y_0-1) >= 0) and ((Y_0-1) <= 7) and ((X_0-1) >= 0) and ((X_0-1) <= 7):
                if (b[Y_0-1,X_0-1] in self.E_list[1]):
                    ib[Y_0-1,X_0-1] = u
                    p[u-1].append(2)
        
    
    def rook_action(self, u, a, i, b):
        Y_m = self.rook_Y[a]
        X_m = self.rook_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0+x*Y_m,X_0+x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]):
                            return (Y_0+i*Y_m), (X_0+i*X_m), self.piece_value_Dict[int(b[Y_0+i*Y_m,X_0+i*X_m])-1]
                        elif (b[Y_0+i*Y_m,X_0+i*X_m] == 0):
                            return (Y_0+i*Y_m), (X_0+i*X_m), 0.5
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0-x*Y_m,X_0-x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]):
                            return (Y_0-i*Y_m), (X_0-i*X_m), self.piece_value_Dict[int(b[Y_0-i*Y_m,X_0-i*X_m])-1]
                        elif (b[Y_0-i*Y_m,X_0-i*X_m] == 0):
                            return (Y_0-i*Y_m), (X_0-i*X_m), 0.5
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            return Y_0, X_0, -2
    
    
    def rook_influence(self, u, b, ib, k, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,4):
                Y_m = self.rook_Y[a]
                X_m = self.rook_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0+i*Y_m,X_0+i*X_m])
                    if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                        if (b[Y_0+i*Y_m,X_0+i*X_m] == 0) or (int(b[Y_0+i*Y_m,X_0+i*X_m][0]) in self.E_list[0]):
                            if i == 1:
                                p[u-1].append(a)
                            ib[Y_0+i*Y_m,X_0+i*X_m] = u
                            if b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]:
                                if b[Y_0+i*Y_m,X_0+i*X_m] == 28:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
        else:
            for a in range(0,4):
                Y_m = self.rook_Y[a]
                X_m = self.rook_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0-i*Y_m,X_0-i*X_m])
                    if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                        if (b[Y_0-i*Y_m,X_0-i*X_m] == 0) or (int(b[Y_0-i*Y_m,X_0-i*X_m][0]) in self.E_list[1]):
                            if i == 1:
                                p[u-1].append(a)
                            ib[Y_0-i*Y_m,X_0-i*X_m] = u
                            if b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]:
                                if b[Y_0-i*Y_m,X_0-i*X_m] == 4:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
    
    
    def knight_action(self, u, a, b):
        Y_m = self.knight_Y[a]
        X_m = self.knight_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):    
                if (b[Y_0+Y_m,X_0+X_m] in self.E_list[0]):
                    return (Y_0+Y_m), (X_0+X_m), self.piece_value_Dict[int(b[Y_0+Y_m,X_0+X_m])-1]
                elif (b[Y_0+Y_m,X_0+X_m] == 0):
                    return (Y_0+Y_m), (X_0+X_m), 0.5
                else:
                    return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):    
                if (b[Y_0-Y_m,X_0-X_m] in self.E_list[1]):
                    return (Y_0-Y_m), (X_0-X_m), self.piece_value_Dict[int(b[Y_0-Y_m,X_0-X_m])-1]
                elif (b[Y_0-Y_m,X_0-X_m] == 0):
                    return (Y_0-Y_m), (X_0-X_m), 0.5
                else:
                    return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
    
    
    def knight_influence(self, u, b, ib, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,8):
                Y_m = self.knight_Y[a]
                X_m = self.knight_X[a]
                if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):
                    if (b[Y_0+Y_m,X_0+X_m] == 0) or (int(b[Y_0+Y_m,X_0+X_m][0]) in self.E_list[0]):
                        p[u-1].append(a)
                        ib[Y_0+Y_m,X_0+X_m] = u
        else:
            for a in range(0,8):
                Y_m = self.knight_Y[a]
                X_m = self.knight_X[a]
                if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):
                    if (b[Y_0-Y_m,X_0-X_m] == 0) or (int(b[Y_0-Y_m,X_0-X_m][0]) in self.E_list[1]):
                        p[u-1].append(a)
                        ib[Y_0-Y_m,X_0-X_m] = u
    
    
    def bishop_action(self, u, a, i, b):
        Y_m = self.bishop_Y[a]
        X_m = self.bishop_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0+x*Y_m,X_0+x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]):
                            return (Y_0+i*Y_m), (X_0+i*X_m), self.piece_value_Dict[int(b[Y_0+i*Y_m,X_0+i*X_m])-1]
                        elif (b[Y_0+i*Y_m,X_0+i*X_m] == -1):
                            return (Y_0+i*Y_m), (X_0+i*X_m), 0.5
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0-x*Y_m,X_0-x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]):
                            return (Y_0-i*Y_m), (X_0-i*X_m), self.piece_value_Dict[int(b[Y_0-i*Y_m,X_0-i*X_m])-1]
                        elif (b[Y_0-i*Y_m,X_0-i*X_m] == -1):
                            return (Y_0-i*Y_m), (X_0-i*X_m), 0.5
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            return Y_0, X_0, -2
        
        
    def bishop_influence(self, u, b, ib, k, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,4):
                Y_m = self.bishop_Y[a]
                X_m = self.bishop_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0+i*Y_m,X_0+i*X_m])
                    if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                        if (b[Y_0+i*Y_m,X_0+i*X_m] == 0) or (int(b[Y_0+i*Y_m,X_0+i*X_m][0]) in self.E_list[0]):
                            p[u-1].append(a)
                            ib[Y_0+i*Y_m,X_0+i*X_m] = u
                            if b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]:
                                if b[Y_0+i*Y_m,X_0+i*X_m] == 28:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
        else:
            for a in range(0,4):
                Y_m = self.bishop_Y[a]
                X_m = self.bishop_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0-i*Y_m,X_0-i*X_m])
                    if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                        if (b[Y_0-i*Y_m,X_0-i*X_m] == 0) or (int(b[Y_0-i*Y_m,X_0-i*X_m][0]) in self.E_list[1]):
                            p[u-1].append(a)
                            ib[Y_0-i*Y_m,X_0-i*X_m] = u
                            if b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]:
                                if b[Y_0-i*Y_m,X_0-i*X_m] == 4:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
    
    
    def king_action(self, u, a, b):
        Y_m = self.king_Y[a]
        X_m = self.king_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):    
                if (b[Y_0+Y_m,X_0+X_m] in self.E_list[0]):
                    return (Y_0+Y_m), (X_0+X_m), self.piece_value_Dict[int(b[Y_0+Y_m,X_0+X_m])-1]
                elif (b[Y_0+Y_m,X_0+X_m] == 0):
                    return (Y_0+Y_m), (X_0+X_m), 0.5
                else:
                    return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
        else:
            if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):    
                if (b[Y_0-Y_m,X_0-X_m] in self.E_list[1]):
                    return (Y_0-Y_m), (X_0-X_m), self.piece_value_Dict[int(b[Y_0-Y_m,X_0-X_m])-1]
                elif (b[Y_0-Y_m,X_0-X_m] == 0):
                    return (Y_0-Y_m), (X_0-X_m), 0.5
                else:
                    return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
    
    
    def king_influence(self, u, b, ib, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,8):
                Y_m = self.king_Y[a]
                X_m = self.king_X[a]
                if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):
                    if (b[Y_0+Y_m,X_0+X_m] == 0) or (int(b[Y_0+Y_m,X_0+X_m][0]) in self.E_list[0]):
                        p[u-1].append(a)
                        ib[Y_0+Y_m,X_0+X_m] = u
        else:
            for a in range(0,8):
                Y_m = self.king_Y[a]
                X_m = self.king_X[a]
                if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):
                    if (b[Y_0-Y_m,X_0-X_m] == 0) or (int(b[Y_0-Y_m,X_0-X_m][0]) in self.E_list[1]):
                        p[u-1].append(a)
                        ib[Y_0-Y_m,X_0-X_m] = u
    
    
    def matilda_action(self, u, a, i, b):
        Y_m = self.queen_Y[a]
        X_m = self.queen_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0+x*Y_m,X_0+x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]):
                            return (Y_0+i*Y_m), (X_0+i*X_m), self.piece_value_Dict[int(b[Y_0+i*Y_m,X_0+i*X_m])-1]
                        elif (b[Y_0+i*Y_m,X_0+i*X_m] == 0):
                            return (Y_0+i*Y_m), (X_0+i*X_m), 0.5
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            else:
                return Y_0, X_0, -2
        else:
            if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                for x in range(1, i+1):
                    if x != i:
                        if b[Y_0-x*Y_m,X_0-x*X_m] == 0:
                            continue
                        else:
                            return Y_0, X_0, -2
                    elif x == i:      
                        if (b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]):
                            return (Y_0-i*Y_m), (X_0-i*X_m), self.piece_value_Dict[int(b[Y_0-i*Y_m,X_0-i*X_m])-1]
                        elif (b[Y_0-i*Y_m,X_0-i*X_m] == 0):
                            return (Y_0-i*Y_m), (X_0-i*X_m), 0.5
                        else:
                            return Y_0, X_0, -2
                    else:
                        return Y_0, X_0, -2
            return Y_0, X_0, -2
    
    
    def matilda_influence(self, u, b, ib, k, p):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,8):
                Y_m = self.queen_Y[a]
                X_m = self.queen_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0+i*Y_m,X_0+i*X_m])
                    if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                        if (b[Y_0+i*Y_m,X_0+i*X_m] == 0) or (int(b[Y_0+i*Y_m,X_0+i*X_m][0]) in self.E_list[0]):
                            p[u-1].append(a)
                            ib[Y_0+i*Y_m,X_0+i*X_m] = u
                            if b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]:
                                if b[Y_0+i*Y_m,X_0+i*X_m] == 28:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
        else:
            for a in range(0,8):
                Y_m = self.queen_Y[a]
                X_m = self.queen_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0-i*Y_m,X_0-i*X_m])
                    if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                        if (b[Y_0-i*Y_m,X_0-i*X_m] == 0) or (int(b[Y_0-i*Y_m,X_0-i*X_m][0]) in self.E_list[1]):
                            p[u-1].append(a)
                            ib[Y_0-i*Y_m,X_0-i*X_m] = u
                            if b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]:
                                if b[Y_0-i*Y_m,X_0-i*X_m] == 4:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
    
    
    def unit_action(self, u, a, i, b):
        if ((u >= 9) and (u <= 16)) or ((u >= 17) and (u <= 24)):
            return self.pawn_action(u, a, b)
        elif (u == 1) or (u == 8) or (u == 25) or (u == 32):
            return self.rook_action(u, a, i, b)
        elif (u == 2) or (u == 7) or (u == 26) or (u == 31):
            return self.knight_action(u, a, b)
        elif (u == 3) or (u == 6) or (u == 27) or (u == 30):
            return self.bishop_action(u, a, i, b)
        elif (u == 4) or (u == 28):
            return self.king_action(u, a, b)
        elif (u == 5) or (u == 29):
            return self.matilda_action(u, a, i, b)
    
    
    def unit_influence(self, u, b, ib, k, p):
        if ((u >= 9) and (u <= 16)) or ((u >= 17) and (u <= 24)):
            return self.pawn_influence(u, b, ib, p)
        elif (u == 1) or (u == 8) or (u == 25) or (u == 32):
            return self.rook_influence(u, b, ib, k, p)
        elif (u == 2) or (u == 7) or (u == 26) or (u == 31):
            return self.knight_influence(u, b, ib, p)
        elif (u == 3) or (u == 6) or (u == 27) or (u == 30):
            return self.bishop_influence(u, b, ib, k, p)
        elif (u == 4) or (u == 28):
            return self.king_influence(u, b, ib, p)
        elif (u == 5) or (u == 29):
            return self.matilda_influence(u, b, ib, k, p)
        
        
        
class Chess():
    def __init__(self):
        self.units = Units()
        self.unit_batches = [[4],[5],[3,6],[2,7],[1,8],[9,10,11,12,13,14,15,16],
                            [17,18,19,20,21,22,23,24],[25,32],[26,31],[27,30],[29],[28]]
        
        
    def init_protocol(self):
        self.board = np.array([[ 1, 2, 3, 4, 5, 6, 7, 8],
                               [ 9,10,11,12,13,14,15,16],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [17,18,19,20,21,22,23,24],
                               [25,26,27,28,29,30,31,32]])
        return self.board.flatten().reshape(1,64).astype('float32')
    
        
    def action_protocol(self, p, u, a, i):
        self.reward = [0.5,0.5,0.5]
        self.influence_board_protocol()
        if np.any(self.board==u):
            if a in self.p_actions[u-1]:
                Y, X, self.reward[2] = self.units.unit_action(u, a, i+1, self.board)
                Y_0, X_0 = np.where(self.board==u)
                self.board[Y,X] = u
                if self.reward[2] != -2:
                    self.board[Y_0,X_0] = 0
                if (self.reward[2] != 0.5) and (self.reward[2] != -2):
                    self.reward[0], self.reward[1] = self.reward[2], self.reward[2]
            else:
                self.reward[1] = -2
        else:
            self.reward[0] = -2
        self.win_check_protocol(p)
        return self.output_board_protocol(), self.reward
            
    
    def output_board_protocol(self):
        self.bcoordinates_list = []
        for x in self.unit_batches:
            temp_bcoordinates = []
            for y in x:
                Temp_Y, Temp_X = np.where(self.board==y)
                temp_bcoordinates.append([Temp_Y,Temp_X])
            self.bcoordinates_list.append(temp_bcoordinates)
        self.output_board = np.zeros((12,8,8))
        z = 0
        for x in self.bcoordinates_list:
            for y in x:
                self.output_board[z,y[0],y[1]] = 1
            z += 1
        return self.output_board.flatten().reshape(1,768).astype('float32')
                
             
    def win_check_protocol(self, p):
        self.influence_board_protocol()
        T = self.surrounded_protocol(p)
        A = len(self.line_of_fire_protocol(p))
        if A > 1:
            if T:
                self.reward[0], self.reward[1], self.reward[2] = 100, 100, 100
        elif A == 1:
            if T:
                if self.protecc_ex_protocol(p) or self.protecc_bl_protocol(p):
                    return
                else:
                    self.reward[0], self.reward[1], self.reward[2] = 100, 100, 100
            else:
                return
        else:
            return
                
    
    def influence_board_protocol(self):
        self.p_actions = [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                          [],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
        self.influence_board = np.zeros((32,8,8))
        self.coordinates_line_of_fire = []
        for y in range(0,8):
            for x in range(0,8):
                if self.board[y,x] != 0:
                    self.units.unit_influence(self.board[y,x], self.board, 
                                              self.influence_board[self.board[y,x]-1], 
                                              self.coordinates_line_of_fire, self.p_actions)
    
    
    def line_of_fire_protocol(self,p):
        self.k_line_of_fire = []
        if p == 0:
            Y_k, X_k = np.where(self.board==28)
            for z in range(0,16):
                if self.influence_board[z,Y_k,X_k]:
                    self.k_line_of_fire.append(self.influence_board[z,Y_k,X_k])
            return self.k_line_of_fire
        else:
            Y_k, X_k = np.where(self.board==4)
            for z in range(16,32):
                if self.influence_board[z,Y_k,X_k]:
                    self.k_line_of_fire.append(self.influence_board[z,Y_k,X_k])
            return self.k_line_of_fire
    
    
    def surrounded_protocol(self,p):
        s = 0
        if p == 0:
            A = np.where(self.influence_board[27]==28)
            for x in range(0,len(A[0])):
                self.influencers = []
                Y_m = A[0][x]
                X_m = A[1][x]
                for z in range(0,16):
                    if self.influence_board[z,Y_m,X_m]:
                        s += 1
                        break
            if s == len(A[0]):
                return True
        else:
            A = np.where(self.influence_board[3]==4)
            for x in range(0,len(A[0])):
                self.influencers = []
                Y_m = A[0][x]
                X_m = A[1][x]
                for z in range(16,32):
                    if self.influence_board[z,Y_m,X_m]:
                        s += 1
                        break
            if s == len(A[0]):
                return True
    
    
    def protecc_ex_protocol(self,p):
        for u in self.k_line_of_fire:
            Y, X = np.where(self.board==u)
            if p == 0:
                for z in range(16,32):
                    if self.influence_board[z,Y,X]:
                        return True
            else:
                for z in range(0,16):
                    if self.influence_board[z,Y,X]:
                        return True
        return False
       
    
    def protecc_bl_protocol(self,p):
        if p == 0:
            for x in self.coordinates_line_of_fire:
                for y in x:
                    for z in range(16,32):
                        if z != 27:
                            if int(self.influence_board[z,y[0],y[1]]):
                                return True
            return False
        else:
            for x in self.coordinates_line_of_fire:
                for y in x:
                    for z in range(0,16):
                        if z != 3:
                            if int(self.influence_board[z,y[0],y[1]]):
                                return True
            return False

game = Chess()
game.init_protocol()
game.action_protocol(1, 32, 0, 3)
game.output_board_protocol()
print(game.reward)

[0.5, -2, 0.5]


In [6]:
import tensorflow as tf
learning_rate = 0.0000001

graph = tf.Graph()
with graph.as_default():
    tf_game_state = tf.placeholder(tf.float32, shape=[1,768])
    
    next_Q = tf.placeholder(tf.float32, shape=[1,224])
    
    weights0 = {'W1' : tf.Variable(tf.random_uniform([768,600])),
                'W2' : tf.Variable(tf.random_uniform([600,500])),
                'W3' : tf.Variable(tf.random_uniform([500,400])),
                'W4' : tf.Variable(tf.random_uniform([400,300])),
                'W5' : tf.Variable(tf.random_uniform([300,224]))
                }
    
    weights1 = {'W1' : tf.Variable(tf.random_uniform([768,600])),
                'W2' : tf.Variable(tf.random_uniform([600,500])),
                'W3' : tf.Variable(tf.random_uniform([500,400])),
                'W4' : tf.Variable(tf.random_uniform([400,300])),
                'W5' : tf.Variable(tf.random_uniform([300,224]))
                }
  
    def Q_function0(x):
        layer_1 = tf.matmul(x, weights0['W1'])
        layer_2 = tf.matmul(tf.nn.relu(layer_1), weights0['W2'])
        layer_3 = tf.matmul(tf.nn.relu(layer_2), weights0['W3'])
        layer_4 = tf.matmul(tf.nn.relu(layer_3), weights0['W4'])
        layer_out = tf.matmul(tf.nn.relu(layer_4), weights0['W5'])
        return layer_out
    
    def Q_function1(x):
        layer_1 = tf.matmul(x, weights1['W1'])
        layer_2 = tf.matmul(tf.nn.relu(layer_1), weights1['W2'])
        layer_3 = tf.matmul(tf.nn.relu(layer_2), weights1['W3'])
        layer_4 = tf.matmul(tf.nn.relu(layer_3), weights1['W4'])
        layer_out = tf.matmul(tf.nn.relu(layer_4), weights1['W5'])
        return layer_out
    
    loss0 = tf.reduce_sum(tf.square(next_Q_units - Q_function0(tf_game_state)))
    loss1 = tf.reduce_sum(tf.square(next_Q_units - Q_function1(tf_game_state)))
    
    trainer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
    
    updateQ0 = trainer.minimize(loss0)
    updateQ1 = trainer.minimize(loss1)
    
    Q_values0 = Q_function0(tf_game_state)
    Q_values1 = Q_function1(tf_game_state)
    
    predict0 = tf.argmax(Q_values0,1)
    predict1 = tf.argmax(Q_values1,1)
    

In [13]:
import random 
game = Chess()
num_eps = 1000
y = 0.9
e_0 = 1
e_1 = 1
win_0 = 0
win_1 = 0
intensity_units = [1,3,5,6,8,25,27,29,30,32]
units_0 = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
units_1 = [16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
actions = [0,1,2,3,4,5,6,7]
intensity = [0,1,2,3,4,5,6]


with tf.Session(graph=graph) as sess:
    tf.global_variables_initializer().run()
    for i in range(1, num_eps+1):
        I = [0]
        turns_0 = 0
        turns_1 = 0
        illegal_0 = 0
        illegal_1 = 0
        s = game.init_protocol()
        rand = False
        t=False
        print('Game: ', i)
        while True:
            U, allU = sess.run([predict_U0,Q_values_U0], feed_dict={tf_game_state:s})
            if np.random.rand(1) < e_0:
                rand = True
                U = random.sample(units_0,1)
            A, allA = sess.run([predict_A0,Q_values_A0], feed_dict={tf_game_state_U:allU})
            if rand:
                A = random.sample(actions,1)
            if (U[0]+1) in intensity_units:
                t = True
                I, allI = sess.run([predict_I0,Q_values_I0], feed_dict={tf_game_state_UA:allA})
                if rand:
                    I = random.sample(intensity,1)
            s1, r = game.action_protocol(0, U[0]+1, A[0], I[0])
            if -2 in r and not(rand):
                illegal_0 += 1
            U1, allU1 = sess.run([predict_U0,Q_values_U0], feed_dict={tf_game_state:s1})
            targetU = allU
            targetU[0,U] = r[0] + y*U1[0]
            _,w1,w2 = sess.run([updateUnits0,weights0['U1'],weights0['U2']],
                               feed_dict={tf_game_state:s,next_Q_units:targetU})
            A1, allA1 = sess.run([predict_A0,Q_values_A0], feed_dict={tf_game_state_U:allU1})
            targetA = allA
            targetA[0,A] = r[1] + y*A1[0]
            _,m1,m2 = sess.run([updateActions0,weights0['A1'],weights0['A2']],
                               feed_dict={tf_game_state_U:allU,next_Q_actions:targetA})
            if t:
                I1 = sess.run([predict_I0], feed_dict={tf_game_state_UA:allA1})
                targetI = allI
                targetI[0,I] = r[2] + y*I1[0]
                _,m1,m2 = sess.run([updateIntensity0,weights0['I1'],weights0['I2']],
                                   feed_dict={tf_game_state_UA:allA,next_Q_intensity:targetI})
            t = False
            if not(rand):
                turns_0 += 1
            rand = False
            I = [0]
            allI = None
            s = s1
            if r[0] == 100:
                print(allU)
                print(game.board)
                if turns_0 == 0:
                    turns_0 += 1
                if turns_1 == 0:
                    turns_1 += 1
                print('Hurray! p1 Turns: ', turns_0, ' Illegal moves(p1, p2): ', illegal_0/turns_0*100, '%', illegal_1/turns_1*100, '%')
                win_0 += 1
                print('Winrate p1: ', win_0/i*100, '%')
                e_0 = 1./((i/10)+1)
                break
            U, allU = sess.run([predict_U1,Q_values_U1], feed_dict={tf_game_state:s})
            if np.random.rand(1) < e_0:
                rand = True
                U = random.sample(units_0,1)
            A, allA = sess.run([predict_A1,Q_values_A1], feed_dict={tf_game_state_U:allU})
            if rand:
                A = random.sample(actions,1)
            if (U[0]+17) in intensity_units:
                t = True
                I, allI = sess.run([predict_I1,Q_values_I1], feed_dict={tf_game_state_UA:allA})
                if rand:
                    I = random.sample(intensity,1)
            s1, r = game.action_protocol(1, U[0]+17, A[0], I[0])
            if -2 in r and not(rand):
                illegal_1 += 1
            U1, allU1 = sess.run([predict_U1,Q_values_U1], feed_dict={tf_game_state:s1})
            targetU = allU
            targetU[0,U] = r[0] + y*U1[0]
            _,w1,w2 = sess.run([updateUnits1,weights1['U1'],weights1['U2']],
                               feed_dict={tf_game_state:s,next_Q_units:targetU})
            A1, allA1 = sess.run([predict_A1,Q_values_A1], feed_dict={tf_game_state_U:allU1})
            targetA = allA
            targetA[0,A] = r[1] + y*A1[0]
            _,m1,m2 = sess.run([updateActions1,weights1['A1'],weights1['A2']],
                               feed_dict={tf_game_state_U:allU,next_Q_actions:targetA})
            if t:
                I1 = sess.run([predict_I1], feed_dict={tf_game_state_UA:allA1})
                targetI = allI
                targetI[0,I] = r[2] + y*I1[0]
                _,m1,m2 = sess.run([updateIntensity1,weights1['I1'],weights1['I2']],
                               feed_dict={tf_game_state_UA:allA,next_Q_intensity:targetI})
            t = False
            if not(rand):
                turns_1 += 1
            rand = False
            I = [0]
            allI = None
            s = s1
            if r[0] == 100:
                print(allU)
                print(game.board)
                if turns_0 == 0:
                    turns_0 += 1
                if turns_1 == 0:
                    turns_1 += 1
                print('Hurray! p2 Turns: ', turns_1, ' Illegal moves(p1, p2): ', illegal_0/turns_0*100, '%', illegal_1/turns_1*100, '%')
                win_1 += 1
                print('Winrate p2: ', win_1/i*100, '%')
                e_1 = 1./((i/10)+1)
                break

Game:  1


D:\Anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:564: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.


[[  1.3272786 -12.535538   25.448513  102.7        -6.220047    5.598668
   -8.4046     27.782967   -2.2636843   3.8767858 -11.952404  -41.025658
  -10.812598  -22.026133  -44.559532  -10.150692 ]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  1  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0 25  0  0  0]]
Hurray! p1 Turns:  1  Illegal moves(p1, p2):  0.0 % 0.0 %
Winrate p1:  100.0 %
Game:  2


D:\Anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:570: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.


[[ 11.111708 -29.72567  -55.28521  -12.641408 -42.29921  -22.766212
  -22.222755 -82.61504  -13.571001 -37.960686 -22.462006 112.6
   12.29141  -78.943886 -40.24376  -43.279842]]
[[ 0  0  0  0 21 24  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  3  0  0]
 [ 0 18  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  0 16]
 [ 0  0  0  0  0  0  0  0]
 [25  0 28  0  0 30  0  0]]
Hurray! p2 Turns:  61  Illegal moves(p1, p2):  64.61538461538461 % 77.04918032786885 %
Winrate p2:  50.0 %
Game:  3
[[-49.10872    18.706516  -25.038168  -19.492548  -53.869476   37.65531
   48.353333  -20.86969   105.4       -61.01991   -86.64837     2.2053986
   29.546448  -36.347588   -3.2341766 -26.41753  ]]
[[ 0  1  3  0  0  0  0  8]
 [ 0 10 26  0  0  0  0  5]
 [ 0 18  0  0  0  0 31  0]
 [ 0  0  0  0 22 14  0 16]
 [ 0  0  0  4 20  0  0 24]
 [ 0  0  0  0  0  0 23 32]
 [17  9  0  0  0  0  0  0]
 [25  0 27  0  0 30  0  0]]
Hurray! p1 Turns:  29  Illegal moves(p1, p2):  68.96551724137932 % 79.310

[[ -68.43346    -22.364494   -28.228928   -43.55784    -56.518204
   -13.510826   -21.92214    -57.241367   -63.10282     -2.411934
   -37.866447   100.9        -56.45955   -102.43347     -1.9220457
    10.900376 ]]
[[ 1  0  3  0  0  6  0 32]
 [ 9  0 26  0  0  0  0  0]
 [17  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0]
 [ 0 10  0 28  0  0 14  0]
 [ 0 18  0  0 21  0  0 15]
 [25  0 27  0 29 30  0  2]]
Hurray! p2 Turns:  201  Illegal moves(p1, p2):  88.0 % 90.04975124378109 %
Winrate p2:  38.88888888888889 %
Game:  19
[[  -6.688236    13.548974    44.7549      39.29525     43.847317
  -115.894615    -7.1089516  -42.27795    111.7         48.59336
    49.430573    -8.057228   -21.921726    58.19964     -3.4971313
    31.828556 ]]
[[ 0 28  0  0  5  6  7  0]
 [ 0  0  0  0  0  0  0  8]
 [ 0 10  0 12  0  0  0 16]
 [ 1  2  0  4  0  0  0 24]
 [ 9  0  0  0  0  0  0  0]
 [17  0  0  0 27 14 15 31]
 [25  0 19  0  0 22 23 32]
 [ 0  0  0  0  0 30  0  0]]
Hurray! p1 Turns:

[[ 10.282032   -2.8846128 -24.161087  109.         -2.6791077  -5.3267746
  -29.12735    10.535103   10.361687   -8.204554    3.3663864   7.9014206
  -65.33684    10.700451   12.869514    2.9331932]]
[[ 0  0  3  0  5  6  0  0]
 [ 0 26 18  0 20  0  0  0]
 [ 0  0  0  0  0 22  0 31]
 [ 0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0 15  8]
 [ 9  0  0  0  0  0 23 16]
 [17  0  0  0  0  0  0 24]
 [ 4  0  0 12 13 30  0 32]]
Hurray! p1 Turns:  438  Illegal moves(p1, p2):  88.81278538812786 % 95.60185185185185 %
Winrate p1:  67.64705882352942 %
Game:  35
[[-54.808624  -14.8178    -24.946861  -58.282143   -5.739979   22.530586
   20.153442  -27.861824   20.862732  -27.898682  -79.97735   105.4
  -21.229643  -24.868952    1.5242004 -51.107452 ]]
[[ 0  0  0  0  0  6 32  0]
 [31  0  0  0  5  0  0  8]
 [ 1  0  0  0 13  0  0  0]
 [ 9  0  0  4 21  0  0  0]
 [17  0  0  0  0 22  0  0]
 [ 0  0  0 20 12 29  0  0]
 [ 0 27  2  0  0  0  0  0]
 [11 26  0  0  0 30  0 16]]
Hurray! p1 Turns:  424  Illegal moves(p1, 

[[ -44.53027   -21.769703  -70.131065  -34.809345  -69.724884  -22.204933
   -96.82948   -31.962605  -41.752895  -64.130844  -64.45432   109.9
   -14.81766   -11.896038  -60.30307  -109.41937 ]]
[[ 1  0  3 28  5  6  7  8]
 [ 9 10  0  0  0 14 15  0]
 [ 0 18  0  0 13  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0 16]
 [ 0  0  0  0  0  0  0  0]
 [17  0 19  0 21 22 23 24]
 [25 26 27  0 29 30 31 32]]
Hurray! p2 Turns:  102  Illegal moves(p1, p2):  94.0 % 90.19607843137256 %
Winrate p2:  36.734693877551024 %
Game:  50
[[-30.1025    -44.369617  -13.743952  -38.90413   -25.709286  -12.441002
  -88.92327   -37.248142  -22.416538  107.2        -3.3239212 -41.608833
  -29.392706  -40.36305     9.55513    13.961866 ]]
[[ 0  0  3  0  0  6  0 32]
 [ 0  0  0  0  0  0  0  0]
 [ 0 10 11  0  0  0  0  0]
 [ 1  0 19  0 26 14  0  0]
 [ 9  0  0 21  5 22  0  0]
 [ 0  0  0 20 13  0 23  7]
 [17 18  0  0 29  0  0  0]
 [25  0 27 28  0 30  0  0]]
Hurray! p2 Turns:  320  Illegal moves(p1, p2):  93.393

KeyboardInterrupt: 

In [139]:
print(game.board)

[[ 1  0  3  0  0  6  0  8]
 [ 0  0 31  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 9  0 20  0  0  0  0 16]
 [17 10  0  0 21 22  0  0]
 [ 0 18 26 29  0  0 23  0]
 [ 0  0 28  0  0  0  0 24]
 [ 0  0 27  0  2 30  0 32]]
