In [98]:
import numpy as np
import time



class Units():
    def __init__(self):
        self.E_list = [[17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32], 
                       [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]
        self.pawn_Y = (1, 1, 1, 2)
        self.pawn_X = (0, -1, 1, 0)
        self.rook_Y = (1, 0, 0, -1)
        self.rook_X = (0, -1, 1, 0)
        self.knight_Y = (2, 1, -1, -2, -2, -1, 1, 2)
        self.knight_X = (1, 2, 2, 1, -1, -2, -2, -1)
        self.bishop_Y = (1, 1, -1, -1)
        self.bishop_X = (-1, 1, 1, -1)
        self.king_Y = (1, 1, 0, -1, -1, -1, 0, 1)
        self.king_X = (0, 1, 1, 1, 0, -1, -1, -1)
        self.queen_Y = (1, 1, 0, -1, -1, -1, 0, 1)
        self.queen_X = (0, 1, 1, 1, 0, -1, -1, -1)
        self.piece_Dict = ("pawn","pawn","pawn","pawn","pawn","pawn","pawn","pawn",
                          "rook","knight","bishop","king","matilda","bishop","knight","rook",
                          "pawn","pawn","pawn","pawn","pawn","pawn","pawn","pawn",
                          "rook","knight","bishop","king","matilda","bishop","knight","rook")
        
        
    def pawn_action(self, u, a, b):
        Y_m = self.pawn_Y[a]
        X_m = self.pawn_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):
                if (Y_0 == 1) and (a == 3):
                    if b[Y_0+1,X_0+1] == 0:
                        if b[Y_0+Y_m,X_0+X_m] == 0:
                            return (Y_0+Y_m), (X_0+X_m), 0
                        else:
                            return Y_0, X_0, -1
                    else:
                        return Y_0, X_0, -1
                elif (a == 1) or (a == 2):
                    if (b[Y_0+Y_m,X_0+X_m] in self.E_list[0]):
                        return (Y_0+Y_m), (X_0+X_m), 1
                    else:
                        return Y_0, X_0, -1
                else:
                    if b[Y_0+Y_m,X_0+Y_m] == 0:
                        return (Y_0+Y_m), X_0, 0
                    else:
                        return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
        else:
            if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):
                if (Y_0 == 1) and (a == 3):
                    if b[Y_0-1,X_0-1] == 0:
                        if b[Y_0-Y_m,X_0] == 0:
                            return (Y_0-Y_m), X_0, 0
                        else:
                            return Y_0, X_0, -1
                    else:
                        return Y_0, X_0, -1
                elif (a == 1) or (a == 2):
                    if (b[Y_0-Y_m,X_0-X_m] in self.E_list[1]):
                        return (Y_0-Y_m), (X_0+X_m), 1
                    else:
                        return Y_0, X_0, -1
                else:
                    if b[Y_0-Y_m,X_0-Y_m] == -1:
                        return (Y_0-Y_m), X_0, 0
                    else:
                        return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
        
        
    def pawn_influence(self, u, b, ib):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+1) >= 0) and ((Y_0+1) <= 7) and (b[Y_0+1,X_0] == 0):
                ib[Y_0+1,X_0] = u
                if ((Y_0+2) >= 0) and ((Y_0+2) <= 7) and (b[Y_0+2,X_0] == 0):
                    ib[Y_0+2,X_0] = u
            if ((Y_0+1) >= 0) and ((Y_0+1) <= 7) and ((X_0+1) >= 0) and ((X_0+1) <= 7):
                if b[Y_0+1,X_0+1] in self.E_list[0]:
                    ib[Y_0+1,X_0+1] = u
            if ((Y_0+1) >= 0) and ((Y_0+1) <= 7) and ((X_0-1) >= 0) and ((X_0-1) <= 7):
                if b[Y_0+1,X_0-1] in self.E_list[0]:
                    ib[Y_0+1,X_0-1] = u
        else:
            if ((Y_0-1) >= 0) and ((Y_0-1) <= 7) and (b[Y_0-1,X_0] == 0):
                ib[Y_0-1,X_0] = u
                if ((Y_0-2) >= 0) and ((Y_0-2) <= 7) and (b[Y_0-2,X_0] == 0):
                    ib[Y_0-2,X_0] = u
            if ((Y_0-1) >= 0) and ((Y_0-1) <= 7) and ((X_0+1) >= 0) and ((X_0+1) <= 7):
                if (b[Y_0-1,X_0+1] in self.E_list[1]):
                    ib[Y_0-1,X_0+1] = u
            if ((Y_0-1) >= 0) and ((Y_0-1) <= 7) and ((X_0-1) >= 0) and ((X_0-1) <= 7):
                if (b[Y_0-1,X_0-1] in self.E_list[1]):
                    ib[Y_0-1,X_0-1] = u
        
    
    def rook_action(self, u, a, i, b):
        Y_m = self.rook_Y[a]
        X_m = self.rook_X[a]
        Y_0, X_0 = np.where(b==u)
        if u <  17:
            if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                for x in range(1, i+1):
                    if (b[Y_0+x*Y_m,X_0+x*X_m] == 0) and (x != i):
                        continue
                    elif x == i:      
                        if (b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]):
                            return (Y_0+i*Y_m), (X_0+i*X_m), 1
                        elif (b[Y_0+i*Y_m,X_0+i*X_m] == -1):
                            return (Y_0+i*Y_m), (X_0+i*X_m), 0
                        else:
                            return Y_0, X_0, -1
                    else:
                        return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
        else:
            if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                for x in range(1, i+1):
                    if (b[Y_0-x*Y_m,X_0-x*X_m] == 0) and (x != i):
                        continue
                    elif x == i:      
                        if (b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]):
                            return (Y_0-i*Y_m), (X_0-i*X_m), 1
                        elif (b[Y_0-i*Y_m,X_0-i*X_m] == -1):
                            return (Y_0-i*Y_m), (X_0-i*X_m), 0
                        else:
                            return Y_0, X_0, -1
                    else:
                        return Y_0, X_0, -1
            return Y_0, X_0, -1
    
    
    def rook_influence(self, u, b, ib, k):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,4):
                Y_m = self.rook_Y[a]
                X_m = self.rook_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0+i*Y_m,X_0+i*X_m])
                    if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                        if (b[Y_0+i*Y_m,X_0+i*X_m] == 0) or (int(b[Y_0+i*Y_m,X_0+i*X_m][0]) in self.E_list[0]):
                            ib[Y_0+i*Y_m,X_0+i*X_m] = u
                            if b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]:
                                if b[Y_0+i*Y_m,X_0+i*X_m] == 28:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
        else:
            for a in range(0,4):
                Y_m = self.rook_Y[a]
                X_m = self.rook_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0-i*Y_m,X_0-i*X_m])
                    if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                        if (b[Y_0-i*Y_m,X_0-i*X_m] == 0) or (int(b[Y_0-i*Y_m,X_0-i*X_m][0]) in self.E_list[1]):
                            ib[Y_0-i*Y_m,X_0-i*X_m] = u
                            if b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]:
                                if b[Y_0-i*Y_m,X_0-i*X_m] == 4:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
    
    
    def knight_action(self, u, a, b):
        Y_m = self.knight_Y[a]
        X_m = self.knight_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):    
                if (b[Y_0+Y_m,X_0+X_m] in self.E_list[0]):
                    return (Y_0+Y_m), (X_0+X_m), 1
                elif (b[Y_0+Y_m,X_0+X_m] == 0):
                    return (Y_0+Y_m), (X_0+X_m), 0
                else:
                    return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
        else:
            if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):    
                if (b[Y_0-Y_m,X_0-X_m] in self.E_list[1]):
                    return (Y_0-Y_m), (X_0-X_m), 1
                elif (b[Y_0-Y_m,X_0-X_m] == 0):
                    return (Y_0-Y_m), (X_0-X_m), 0
                else:
                    return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
    
    
    def knight_influence(self, u, b, ib):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,8):
                Y_m = self.knight_Y[a]
                X_m = self.knight_X[a]
                if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):
                    if (b[Y_0+Y_m,X_0+X_m] == 0) or (int(b[Y_0+Y_m,X_0+X_m][0]) in self.E_list[0]):
                        ib[Y_0+Y_m,X_0+X_m] = u
        else:
            for a in range(0,8):
                Y_m = self.knight_Y[a]
                X_m = self.knight_X[a]
                if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):
                    if (b[Y_0-Y_m,X_0-X_m] == 0) or (int(b[Y_0-Y_m,X_0-X_m][0]) in self.E_list[1]):
                        ib[Y_0-Y_m,X_0-X_m] = u
    
    
    def bishop_action(self, u, a, i, b):
        Y_m = self.bishop_Y[a]
        X_m = self.bishop_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                for x in range(1, i+1):
                    if (b[Y_0+x*Y_m,X_0+x*X_m] == 0) and (x != i):
                        continue
                    elif x == i:      
                        if (b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]):
                            return (Y_0+i*Y_m), (X_0+i*X_m), 1
                        elif (b[Y_0+i*Y_m,X_0+i*X_m] == -1):
                            return (Y_0+i*Y_m), (X_0+i*X_m), 0
                        else:
                            return Y_0, X_0, -1
                    else:
                        return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
        else:
            if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                for x in range(1, i+1):
                    if (b[Y_0-x*Y_m,X_0-x*X_m] == 0) and (x != i):
                        continue
                    elif x == i:      
                        if (b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]):
                            return (Y_0-i*Y_m), (X_0-i*X_m), 1
                        elif (b[Y_0-i*Y_m,X_0-i*X_m] == -1):
                            return (Y_0-i*Y_m), (X_0-i*X_m), 0
                        else:
                            return Y_0, X_0, -1
                    else:
                        return Y_0, X_0, -1
            return Y_0, X_0, -1
        
        
    def bishop_influence(self, u, b, ib, k):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,4):
                Y_m = self.bishop_Y[a]
                X_m = self.bishop_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0+i*Y_m,X_0+i*X_m])
                    if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                        if (b[Y_0+i*Y_m,X_0+i*X_m] == 0) or (int(b[Y_0+i*Y_m,X_0+i*X_m][0]) in self.E_list[0]):
                            ib[Y_0+i*Y_m,X_0+i*X_m] = u
                            if b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]:
                                if b[Y_0+i*Y_m,X_0+i*X_m] == 28:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
        else:
            for a in range(0,4):
                Y_m = self.bishop_Y[a]
                X_m = self.bishop_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0-i*Y_m,X_0-i*X_m])
                    if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                        if (b[Y_0-i*Y_m,X_0-i*X_m] == 0) or (int(b[Y_0-i*Y_m,X_0-i*X_m][0]) in self.E_list[1]):
                            ib[Y_0-i*Y_m,X_0-i*X_m] = u
                            if b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]:
                                if b[Y_0-i*Y_m,X_0-i*X_m] == 4:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
    
    
    def king_action(self, u, a, b):
        Y_m = self.king_Y[a]
        X_m = self.king_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):    
                if (b[Y_0+Y_m,X_0+X_m] in self.E_list[0]):
                    return (Y_0+Y_m), (X_0+X_m), 1
                elif (b[Y_0+Y_m,X_0+X_m] == 0):
                    return (Y_0+Y_m), (X_0+X_m), 0
                else:
                    return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
        else:
            if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):    
                if (b[Y_0-Y_m,X_0-X_m] in self.E_list[1]):
                    return (Y_0-Y_m), (X_0-X_m), 1
                elif (b[Y_0-Y_m,X_0-X_m] == 0):
                    return (Y_0-Y_m), (X_0-X_m), 0
                else:
                    return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
    
    
    def king_influence(self, u, b, ib):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,8):
                Y_m = self.king_Y[a]
                X_m = self.king_X[a]
                if ((Y_0+Y_m) >= 0) and ((Y_0+Y_m) <= 7) and ((X_0+X_m) >= 0) and ((X_0+X_m) <= 7):
                    if (b[Y_0+Y_m,X_0+X_m] == 0) or (int(b[Y_0+Y_m,X_0+X_m][0]) in self.E_list[0]):
                        ib[Y_0+Y_m,X_0+X_m] = u
        else:
            for a in range(0,8):
                Y_m = self.king_Y[a]
                X_m = self.king_X[a]
                if ((Y_0-Y_m) >= 0) and ((Y_0-Y_m) <= 7) and ((X_0-X_m) >= 0) and ((X_0-X_m) <= 7):
                    if (b[Y_0-Y_m,X_0-X_m] == 0) or (int(b[Y_0-Y_m,X_0-X_m][0]) in self.E_list[1]):
                        ib[Y_0-Y_m,X_0-X_m] = u
    
    
    def matilda_action(self, u, a, i, b, k):
        Y_m = self.queen_Y[a]
        X_m = self.queen_X[a]
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                for x in range(1, i+1):
                    if (b[Y_0+x*Y_m,X_0+x*X_m] == -1) and (x != i):
                        continue
                    elif x == i:      
                        if (b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]):
                            return (Y_0+i*Y_m), (X_0+i*X_m), 1
                        elif (b[Y_0+i*Y_m,X_0+i*X_m] == 0):
                            return (Y_0+i*Y_m), (X_0+i*X_m), 0
                        else:
                            return Y_0, X_0, -1
                    else:
                        return Y_0, X_0, -1
            else:
                return Y_0, X_0, -1
        else:
            if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                for x in range(1, i+1):
                    if (b[Y_0-x*Y_m,X_0-x*X_m] == -1) and (x != i):
                        continue
                    elif x == i:      
                        if (b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]):
                            return (Y_0-i*Y_m), (X_0-i*X_m), 1
                        elif (b[Y_0-i*Y_m,X_0-i*X_m] == 0):
                            return (Y_0-i*Y_m), (X_0-i*X_m), 0
                        else:
                            return Y_0, X_0, -1
                    else:
                        return Y_0, X_0, -1
            return Y_0, X_0, -1
    
    
    def matilda_influence(self, u, b, ib, k):
        Y_0, X_0 = np.where(b==u)
        if u < 17:
            for a in range(0,8):
                Y_m = self.queen_Y[a]
                X_m = self.queen_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0+i*Y_m,X_0+i*X_m])
                    if ((Y_0+i*Y_m) >= 0) and ((Y_0+i*Y_m) <= 7) and ((X_0+i*X_m) >= 0) and ((X_0+i*X_m) <= 7):
                        if (b[Y_0+i*Y_m,X_0+i*X_m] == 0) or (int(b[Y_0+i*Y_m,X_0+i*X_m][0]) in self.E_list[0]):
                            ib[Y_0+i*Y_m,X_0+i*X_m] = u
                            if b[Y_0+i*Y_m,X_0+i*X_m] in self.E_list[0]:
                                if b[Y_0+i*Y_m,X_0+i*X_m] == 28:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
        else:
            for a in range(0,8):
                Y_m = self.queen_Y[a]
                X_m = self.queen_X[a]
                temp_coordinates = []
                for i in range(1,8):
                    temp_coordinates.append([Y_0-i*Y_m,X_0-i*X_m])
                    if ((Y_0-i*Y_m) >= 0) and ((Y_0-i*Y_m) <= 7) and ((X_0-i*X_m) >= 0) and ((X_0-i*X_m) <= 7):
                        if (b[Y_0-i*Y_m,X_0-i*X_m] == 0) or (int(b[Y_0-i*Y_m,X_0-i*X_m][0]) in self.E_list[1]):
                            ib[Y_0-i*Y_m,X_0-i*X_m] = u
                            if b[Y_0-i*Y_m,X_0-i*X_m] in self.E_list[1]:
                                if b[Y_0-i*Y_m,X_0-i*X_m] == 4:
                                    k.append(temp_coordinates)
                                break
                        else:
                            break
                    else:
                        break
    
    
    def unit_action(self, u, a, i, b):
        if ((u >= 9) and (u <= 16)) or ((u >= 17) and (u <= 24)):
            return self.pawn_influence(u, b, ib)
        elif (u == 1) or (u == 8) or (u == 25) or (u == 32):
            return self.rook_action(u, a, i, b)
        elif (u == 2) or (u == 7) or (u == 26) or (u == 31):
            return self.knight_action(u, a, b)
        elif (u == 3) or (u == 6) or (u == 27) or (u == 30):
            return self.bishop_action(u, a, i, b)
        elif (u == 4) or (u == 28):
            return self.king_action(u, a, b)
        elif (u == 5) or (u == 29):
            return self.matilda_action(u, a, i, b)
    
    
    def unit_influence(self, u, b, ib, k):
        if ((u >= 9) and (u <= 16)) or ((u >= 17) and (u <= 24)):
            return self.pawn_influence(u, b, ib)
        elif (u == 1) or (u == 8) or (u == 25) or (u == 32):
            return self.rook_influence(u, b, ib, k)
        elif (u == 2) or (u == 7) or (u == 26) or (u == 31):
            return self.knight_influence(u, b, ib)
        elif (u == 3) or (u == 6) or (u == 27) or (u == 30):
            return self.bishop_influence(u, b, ib, k)
        elif (u == 4) or (u == 28):
            return self.king_influence(u, b, ib)
        elif (u == 5) or (u == 29):
            return self.matilda_influence(u, b, ib, k)
        
        
        
class Chess():
    def __init__(self):
        self.units = Units()
        
        
    def init_protocol(self):
        self.reward = [0, 0]
        self.board = np.array([[ 1, 2, 3, 4, 5, 6, 7, 8],
                               [ 9,10,11, 0,13,14,15,16],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [ 0, 0, 0, 0, 0, 0, 0, 0],
                               [ 0, 0, 0,29, 0, 0, 0, 0],
                               [17,18,19,20,21,22,23,24],
                               [25,26,27,28, 0,30,31,32]])
        
        
    def action_protocol(self, p, u, a, i):
        if np.any(self.board==u):
            Y, X, self.reward = self.units.unit_action(p, u, a, i, self.board, 0)
            Y_0, X_0 = np.where(self.board==u)
            self.board[Y,X] = u
            if (self.reward == 1) or (self.reward == 0):
                self.board[Y_0,X_0] = 0
        else:
            self.reward = -1
            
    
    def win_check_protocol(self, p):
        self.influence_board_protocol()
        temp1, temp2 = p%2, (p+1)%2
        A = len(self.line_of_fire_protocol(p))
        if A > 1:
            if self.surrounded_protocol(p):
                self.reward[temp1], self.reward[temp2] = 100, -100
        elif A == 1:
            print(self.protecc_ex_protocol(p))
            print(self.protecc_bl_protocol(p))
            if self.protecc_ex_protocol(p) or self.protecc_bl_protocol(p):
                return
            else:
                self.reward[temp1], self.reward[temp2] = 100, -100
        else:
            return
                
    
    def influence_board_protocol(self):
        self.influence_board = np.zeros((32,8,8))
        self.coordinates_line_of_fire = []
        for y in range(0,8):
            for x in range(0,8):
                if self.board[y,x] != 0:
                    self.units.unit_influence(self.board[y,x], self.board, 
                                              self.influence_board[self.board[y,x]-1], self.coordinates_line_of_fire)
    
    
    def line_of_fire_protocol(self,p):
        self.k_line_of_fire = []
        if p == 0:
            Y_k, X_k = np.where(self.board==28)
            for z in range(0,16):
                if self.influence_board[z,Y_k,X_k]:
                    self.k_line_of_fire.append(self.influence_board[z,Y_k,X_k])
            return self.k_line_of_fire
        else:
            Y_k, X_k = np.where(self.board==4)
            for z in range(16,32):
                if self.influence_board[z,Y_k,X_k]:
                    self.k_line_of_fire.append(self.influence_board[z,Y_k,X_k])
            return self.k_line_of_fire
    
    
    def surrounded_protocol(self,p):
        s = 0
        if p == 0:
            A = np.where(self.influence_board[27]==28)
            for x in range(0,len(A[0])):
                self.influencers = []
                Y_m = A[0][x]
                X_m = A[1][x]
                for z in range(0,16):
                    if self.influence_board[z,Y_m,X_m]:
                        s += 1
                        break
            if s == len(A[0]):
                return True
        else:
            A = np.where(self.influence_board[3]==4)
            for x in range(0,len(A[0])):
                self.influencers = []
                Y_m = A[0][x]
                X_m = A[1][x]
                for z in range(16,32):
                    if self.influence_board[z,Y_m,X_m]:
                        s += 1
                        break
            if s == len(A[0]):
                return True
    
    
    def protecc_ex_protocol(self,p):
        for u in self.k_line_of_fire:
            Y, X = np.where(self.board==u)
            if p == 0:
                for z in range(16,32):
                    if self.influence_board[z,Y,X]:
                        return True
            else:
                for z in range(0,16):
                    if self.influence_board[z,Y,X]:
                        return True
        return False
       
    
    def protecc_bl_protocol(self,p):
        if p == 0:
            for x in self.coordinates_line_of_fire:
                for y in x:
                    for z in range(16,32):
                        if z != 27:
                            if int(self.influence_board[z,y[0],y[1]]):
                                return True
            return False
        else:
            for x in self.coordinates_line_of_fire:
                for y in x:
                    for z in range(0,16):
                        if z != 3:
                            if int(self.influence_board[z,y[0],y[1]]):
                                return True
            return False


In [4]:
import tensorflow as tf

hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

b'Hello, TensorFlow!'


In [99]:
game = Chess()
game.init_protocol()
print(game.board)
t0 = time.time()
game.win_check_protocol(1)
t = time.time()-t0
print(game.influence_board[29])
print(game.reward)
print(t)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11  0 13 14 15 16]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 29  0  0  0  0]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28  0 30 31 32]]
False
True
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[0, 0]
0.0070035457611083984
